### ISSUE TITLE
Add Navbar and Footer

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/Hacktoberfest#4]
## Add navbar and footer in the index.html so that the website will look amazing

**Comment by imkks** [comment]
I want to work on it, Please assign it to me

**Comment by bucharitesh** [comment]
hey @Sanchitbajaj02 please assign it to me

**Comment by bucharitesh** [comment]
done please check and close :) If you need any other help please connect to me on contact@bucharitesh.in

**Comment by Sanchitbajaj02** [comment]
> done please check and close :) If you need any other help please connect to me on [contact@bucharitesh.in](mailto:contact@bucharitesh.in)

ok I'll check

**Comment by Sanchitbajaj02** [comment]
@bucharitesh code is taking so much time while loading and also heavily conflicting with other commits.

Can you please optimize your code after c63bef0 this commit

**Comment by Sanchitbajaj02** [comment]
@bucharitesh also mention what you have done in README

**Comment by bucharitesh** [comment]
Okayy noted
